FROM python:3.8-slim-buster

RUN useradd slang

WORKDIR /home/app

COPY requirements.txt requirements.txt

RUN python -m venv venv
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2

RUN venv/bin/pip install -r requirements.txt

COPY app app
COPY migrations migrations
COPY straattaal.py config.py boot_dev.sh tests.py ./
RUN chmod +x boot_dev.sh
COPY data data

ENV FLASK_APP straattaal.py

RUN chown -R slang:slang ./
USER slang

ENTRYPOINT ["./boot_dev.sh"]
