name: straattaal
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy==1.19.5
  - importlib-metadata==4.6.1
  - alembic==1.6.5
  - greenlet==1.1.0
  - zipp==3.5.0
  - dataclasses==0.8
  - flask-wtf==0.15.1
  - mako==1.1.4
  - requests==2.25.1
  - flask-login==0.5.0
  - email-validator==1.1.3
  - flask-sqlalchemy==2.5.1
  - chardet==4.0.0
  - six==1.16.0
  - wtforms==2.3.3
  - python-dateutil==2.8.1
  - itsdangerous==2.0.1
  - typing-extensions==3.10.0.0
  - python-dotenv==0.18.0
  - dnspython==2.1.0
  - urllib3==1.26.6
  - werkzeug==2.0.1
  - certifi==2021.5.30
  - idna==2.10
  - pytorch==1.8.0
  - markupsafe==2.0.1
  - flask==2.0.1
  - jinja2==3.0.1
  - sqlalchemy==1.4.20
  - psycopg2-binary==2.9.1
  - click==8.0.1
  - flask-migrate==3.0.1
  - python-editor==1.0.4
