"""slang table

Revision ID: 3622b1ed7dfb
Revises: 79bf0dddc7f6
Create Date: 2021-07-11 09:28:56.077224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3622b1ed7dfb"
down_revision = "79bf0dddc7f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slang",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word", sa.String(length=56), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("slang")
    # ### end Alembic commands ###
