"""Update Model database model.

Revision ID: 36cf0bd74166
Revises: a6030a90b804
Create Date: 2021-07-24 21:18:29.724426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36cf0bd74166'
down_revision = 'a6030a90b804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('model', sa.String(length=64), nullable=True))
    op.drop_column('model', 'word')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('word', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('model', 'model')
    # ### end Alembic commands ###
