"""Create/Update meaning, model, and word database models.

Revision ID: a6030a90b804
Revises: 990d4ed9bb61
Create Date: 2021-07-24 20:46:05.967406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6030a90b804'
down_revision = '990d4ed9bb61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meaning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meaning', sa.String(length=140), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('word', sa.Column('model_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'word', 'model', ['model_id'], ['id'])
    op.drop_column('word', 'type')
    op.drop_column('word', 'meaning')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('meaning', sa.VARCHAR(length=280), autoincrement=False, nullable=True))
    op.add_column('word', sa.Column('type', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'word', type_='foreignkey')
    op.drop_column('word', 'model_id')
    op.drop_table('meaning')
    op.drop_table('model')
    # ### end Alembic commands ###
