"""slang table

Revision ID: c331041334ca
Revises: 3622b1ed7dfb
Create Date: 2021-07-11 09:32:34.290963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c331041334ca"
down_revision = "3622b1ed7dfb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("slang", sa.Column("meaning", sa.String(length=280), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("slang", "meaning")
    # ### end Alembic commands ###
