"""Update Model database model.

Revision ID: d1a4e1ed440f
Revises: 36cf0bd74166
Create Date: 2021-07-24 21:19:17.941807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a4e1ed440f'
down_revision = '36cf0bd74166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('model_type', sa.String(length=64), nullable=True))
    op.drop_column('model', 'model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('model', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('model', 'model_type')
    # ### end Alembic commands ###
